# 6. get list of characters 
to feed into chatgpt for sentence examples

In [1]:
import pandas as pd

In [236]:
i = 0
chunk_size = 200
while (chunk_size*i) < len(df_hsk):
    print(chunk_size*i, chunk_size*(i+1) - 1, len(df_hsk))
    print(df_hsk['chinese'].loc[chunk_size*i:chunk_size*(i+1) - 1].values)
    i += 1

0 199 1134
['挨着' '挨' '安检' '罢工' '挨打' '白领' '办公' '百分点' '办学' '办事处' '半决赛' '罢了' '保健' '报刊'
 '傍晚' '暴风雨' '抱歉' '暴露' '报考' '爆' '暴雨' '爆炸' '暴力' '悲惨' '爆发' '背着' '背心' '本' '奔跑'
 '被告' '本期' '本身' '本质' '本土' '逼' '本地' '必将' '笔试' '边缘' '必修' '闭' '扁' '编制' '变更'
 '变形' '变换' '便是' '便' '遍地' '表面上' '病情' '拨打' '病房' '波浪' '播' '波动' '不见' '不便' '不再'
 '不料' '不至于' '补考' '补习' '补课' '补助' '不成' '捕' '不禁' '不仅仅' '不通' '不怎么样' '不值' '不怎么'
 '布满' '部队' '采纳' '参赛' '踩' '参展' '餐' '残疾' '残疾人' '残酷' '仓库' '惨' '藏' '操纵' '侧'
 '厕所' '测定' '策划' '策略' '层面' '差异' '查出' '查看' '拆迁' '产量' '昌盛' '长假' '长短' '长跑'
 '长远' '常规' '长久' '常年' '场地' '厂商' '场馆' '场景' '畅通' '超出' '炒' '超' '炒股' '车号' '炒作'
 '车展' '车牌' '撤销' '撤离' '撑' '成分' '成品' '承诺' '城区' '城乡' '城镇' '成' '冲击' '持有' '重建'
 '宠物' '崇拜' '重组' '冲' '出场' '出动' '出访' '出路' '出面' '出入' '出事' '出名' '出台' '初等' '除'
 '出行' '厨师' '储存' '处处' '处长' '传输' '传媒' '传言' '传出' '船员' '船只' '船长' '串' '窗口' '创建'
 '创意' '创办' '此处' '此前' '此次' '此事' '次数' '此致' '从不' '从没' '醋' '村庄' '搭' '错过' '搭配'
 '搭档' '打动' '打断' '打牌' '打发' '打官司' '打印机' '大道' '打造' '大街' '大米' '大批' '大赛' '大师'
 '大力' '大使' '待会儿' '担忧' '诞生' '单打' '党' '当' '当天']
200 399 1134
['当成' '档' '当作' '档案' '到期' '盗版' '岛' '道教' '道歉' '低温' '低头' '抵达' '抵抗' '地名' '地板'
 '地下室' '电动' '滴' '电车' '电器' '电力' '吊' '调研' '定价' '定时' '跌' '定位' '斗争' '动画' '毒品'
 '赌' '赌博' '端' '都市' '端午节' '短片' '渡' '队伍' '对外' '对抗' '多半' '多方面' '多媒体' '夺' '蹲'
 '夺取' '恩人' '儿科' '发病' '发电' '发放' '发起' '发怒' '发言人' '法庭' '发炎' '番' '番茄' '凡是'
 '法语' '繁殖' '反问' '反响' '犯规' '犯' '反抗' '犯罪' '防守' '房价' '防范' '仿佛' '飞船' '飞行员' '肺'
 '分工' '愤怒' '分裂' '峰会' '奉献' '风暴' '佛教' '佛' '服' '父女' '父子' '负' '浮' '妇女' '副'
 '复苏' '富人' '改装' '干涉' '肝' '富有' '杆' '赶不上' '赶上' '赶忙' '刚好' '感人' '岗位' '港口' '高层'
 '敢于' '高档' '高峰' '高等' '高考' '高科技' '稿子' '高手' '歌词' '歌星' '革新' '工商' '公' '更是'
 '公鸡' '公众' '公安' '歌唱' '攻击' '供给' '宫' '公主' '巩固' '贡献' '孤独' '孤儿' '古典' '构建' '股'
 '姑姑' '股票' '故障' '顾' '刮' '拐' '关爱' '关联' '观光' '官司' '管道' '广阔' '股东' '光辉' '轨道'
 '跪' '国产' '国会' '国旗' '国王' '果酱' '果树' '国歌' '过后' '过渡' '海报' '过时' '海浪' '海外' '海底'
 '海军' '海洋' '海湾' '好转' '好容易' '好学' '好似' '合约' '核心' '黑夜' '和谐' '很难说' '横' '衡量'
 '狠' '宏大' '洪水' '互动' '忽略' '户外' '护' '花瓶' '花费' '花生' '化解' '幻想' '壶' '患者' '回应'
 '皇帝' '会见' '会长' '毁' '混' '绘画' '混乱' '混合']
400 599 1134
['活跃' '火箭' '机动车' '昏' '机关' '基督教' '机械' '激情' '吉祥' '极端' '急救' '集' '疾病' '加盟'
 '吉利' '家电' '家园' '嘉宾' '给予' '假日' '监督' '监测' '捡' '简介' '剑' '鉴定' '箭' '将军' '讲课'
 '酱' '骄傲' '酱油' '焦点' '尖' '脚印' '教堂' '教育部' '接收' '街头' '觉' '节' '节假日' '节能' '杰出'
 '揭' '截止' '解' '解说' '截至' '界' '金额' '节奏' '借鉴' '金钱' '尽' '进攻' '近日' '近视' '惊人'
 '精' '精美' '精品' '井' '惊喜' '金融' '景点' '纠纷' '纠正' '净' '酒水' '救命' '救援' '救助' '景'
 '就算' '就是说' '据' '捐' '局' '捐款' '捐赠' '捐助' '剧' '决策' '觉悟' '绝' '绝大多数' '军舰' '军事'
 '军队' '开关' '开创' '开通' '开设' '开夜车' '看得见' '开头' '看' '看管' '看得起' '看作' '康复' '看好'
 '考场' '抗议' '科研' '客车' '考题' '空军' '肯' '口试' '扣' '跨' '快车' '酷' '矿' '宽阔' '阔' '来往'
 '赖' '啦' '蓝天' '栏目' '蓝领' '牢' '老乡' '冷气' '冷水' '理财' '礼堂' '理' '力' '理智' '联盟' '利'
 '懒' '联赛' '凉鞋' '两侧' '两手' '聊天儿' '聊' '联手' '灵活' '裂' '料' '领袖' '留言' '另' '流感'
 '楼道' '楼房' '领取' '陆军' '录像' '露' '录音机' '旅店' '马车' '路过' '埋' '绿化' '慢车' '馒头' '盲人'
 '嘛' '梅花' '美容' '猛' '蒙' '免得' '棉' '面对面' '面向' '妙' '灭' '民歌' '民工' '民警' '民主'
 '名胜' '名额' '民意' '名誉' '名义' '命' '明日' '磨' '没收' '膜' '墨水' '母' '母鸡' '母女' '墓'
 '拿走' '母子' '奶粉' '难忘' '奶牛']
600 799 1134
['内外' '内地' '内衣' '能否' '泥' '扭' '排行榜' '判' '派出' '盼望' '泡' '陪同' '皮球' '配置' '偏'
 '贫困' '聘请' '炮' '品牌' '平凡' '平衡' '评' '平台' '屏幕' '评选' '扑' '平方米' '铺' '奇妙' '坡'
 '欺负' '企图' '气氛' '恰当' '恰好' '起诉' '恰恰' '铅笔' '谦虚' '牵' '起点' '前方' '强盗' '潜力' '前来'
 '强势' '强壮' '巧妙' '桥梁' '强化' '切实' '侵犯' '茄子' '亲属' '倾向' '清' '清洁' '清洁工' '亲眼'
 '清明节' '情绪' '球拍' '清洗' '球星' '求职' '球员' '渠道' '取款' '去掉' '区分' '取款机' '权' '全力'
 '权力' '全新' '券' '缺陷' '让座' '热点' '热水' '热水器' '热线' '人权' '日夜' '却是' '认同' '融合'
 '融入' '日语' '如' '如一' '乳制品' '入' '入学' '若' '塞' '赛' '赛场' '三明治' '山峰' '山谷' '丧失'
 '伤口' '伤亡' '山坡' '伤员' '商城' '上市' '上当' '上演' '上帝' '上台' '勺' '舌头' '少儿' '设计师'
 '深化' '涉及' '深深' '审查' '升级' '升学' '生活费' '省钱' '升值' '圣诞节' '师父' '盛行' '时节' '师生'
 '时时' '时期' '时装' '时而' '识' '实践' '食欲' '市民' '试点' '适当' '事后' '收藏' '识字' '收养'
 '手续费' '收取' '首' '首脑' '首席' '首次' '书房' '首相' '薯片' '双打' '爽' '水泥' '税' '顺' '薯条'
 '说明书' '司长' '说实话' '死亡' '四处' '寺' '送礼' '送行' '素质' '算是' '虽' '算了' '踏实' '岁数' '塔'
 '踏' '所' '台灯' '叹气' '探索' '太阳能' '探讨' '趟' '掏' '特大' '特地' '特' '特快' '疼痛' '特意'
 '踢' '提交' '提升' '天然' '天堂' '田' '天下' '添' '田径' '跳水' '通报']
800 999 1134
['听取' '通道' '通红' '通行' '通话' '同' '同胞' '同期' '通讯' '同行' '铜牌' '同一' '头疼' '投票' '图书'
 '透露' '途径' '徒弟' '土' '团队' '退票' '吞' '推出' '托' '拖' '拖鞋' '挖' '娃娃' '外币' '外部'
 '外出' '哇' '外科' '外观' '外衣' '外来' '外资' '外头' '弯曲' '顽皮' '顽强' '王后' '王子' '往后' '网吧'
 '网页' '往年' '望见' '危机' '威胁' '往来' '微波炉' '维生素' '为此' '为何' '卧铺' '文娱' '无边' '乌云'
 '无关' '物品' '无效' '误' '舞蹈' '西班牙语' '吸毒' '牺牲' '洗衣粉' '细胞' '戏曲' '细菌' '先锋' '嫌'
 '显出' '险' '陷入' '响声' '线路' '想不到' '消耗' '消灭' '小费' '小麦' '小于' '笑脸' '晓得' '笑容'
 '笑声' '协会' '协商' '协调' '写字楼' '协助' '写字台' '心愿' '心脏' '心灵' '心脏病' '新人' '新兴' '薪水'
 '信仰' '信用' '行程' '兴旺' '形' '凶手' '袖珍' '修车' '凶' '悬' '旋转' '选拔' '学会' '选举' '学员'
 '血液' '血管' '压迫' '循环' '烟花' '沿海' '沿' '沿着' '研发' '眼看' '演奏' '宴会' '仰' '洋' '养老'
 '样' '氧气' '药品' '要不然' '要好' '要么' '要素' '野' '野生' '医药' '依次' '依赖' '一次性' '一道'
 '一代' '一贯' '一路上' '仪器' '仪式' '一番' '遗憾' '一模一样' '一时' '一同' '一齐' '一行' '艺人' '议题'
 '异常' '意想不到' '意愿' '因素' '因' '阴谋' '音量' '阴影' '音像' '隐私' '隐藏' '印' '迎来' '英雄'
 '影迷' '影星' '用处' '应急' '用法' '用得着' '应对' '用心' '优质' '用品' '游玩' '游人' '游戏机' '游行'
 '有关' '有没有' '有事' '于' '娱乐' '愉快' '与' '宇航员' '预约' '雨衣' '元素' '园' '园地']
1000 1199 1134
['原' '原告' '原谅' '圆珠笔' '缘故' '援助' '远远' '远离' '远方' '晕' '约定' '运作' '乐曲' '允许' '晕车'
 '杂' '再生' '再说' '遭到' '遭受' '遭遇' '早晚' '增进' '扎' '增值' '炸弹' '扎实' '炸' '债' '炸药'
 '占据' '战场' '战术' '战略' '战友' '章' '站台' '掌声' '长' '账' '账户' '涨' '招' '障碍' '照样'
 '照耀' '招聘' '哲学' '这就是说' '镇' '争夺' '整顿' '正当' '整治' '政策' '政权' '症状' '政党' '之类'
 '支援' '支撑' '知名' '织' '枝' '直升机' '职责' '止' '只得' '只顾' '只管' '指数' '指定' '指头' '指着'
 '至于' '智慧' '治病' '中华' '中等' '中外' '中期' '忠心' '肿' '钟头' '种种' '珠宝' '诸位' '主持人' '粥'
 '主角' '煮' '主流' '住宅' '驻' '柱子' '专用' '祝愿' '转动' '转' '赚钱' '壮观' '赚' '追究' '装备'
 '自来水' '咨询' '捉' '自我' '自学' '自言自语' '自在' '宗教' '总部' '总经理' '总监' '总量' '走私' '奏'
 '租金' '足' '足以' '祖父' '族' '祖国' '祖母' '最终' '罪' '钻' '罪恶' '作' '最佳' '作废' '座谈会'
 '作战']

# 4. Raw hsk file combine with example sentences and cat from chatgpt

In [237]:
# Enhance sentences with hsk3.0 info for final file
hsk_level = '6'
df_hsk = pd.read_csv(f'static/hsk/raw/HSK {hsk_level}.tsv', delimiter='\t', header=None).rename(columns={0:'trad', 1:'chinese', 2:'hsk3.0_pinyin', 3: 'hsk3.0_def'})
df_hsk['video_notes'] = df_hsk['hsk3.0_def'].apply(lambda x: f"HSK3.0 definition: {x}")
df_hsk =df_hsk.reset_index()
# df_hsk['category'] = 'tmp'
# df_hsk['pinyin'] = 'tmp'
# df_hsk['english'] = 'me'
# df_hsk['sentence'] = '保险'
# df_hsk['sentence_pinyin'] = 'tmp'
# df_hsk['sentence_english'] = 'me'
df_hsk.to_csv(f'static/hsk/intermediate/HSK{hsk_level}_present.csv')
df_hsk.sample(5)

# Sentence prompt
# Give sentence examples for the list of chinese words below. output is csv with 6 columns: simplified chinese, pinyin, english translation, example sentence in simplified chinese, sentence pinyin, sentence english. DO NOT use commas except for as required as separators in the csv format! also remember to use a variety of sentence structure and common applications of words.

dfsent = pd.read_csv(f'static/hsk/intermediate/HSK{hsk_level}_sent_raw.csv')
dfsent = df_hsk[['index', 'chinese', 'trad', 'hsk3.0_pinyin', 'hsk3.0_def', 'video_notes']].merge(dfsent, on='chinese')
# dfsent['category'] = 'tmp'
dfsent.to_csv(f'static/hsk/intermediate/HSK{hsk_level}_sent_nocat.csv', index=False)
dfsent.sample(5)

df_cat = pd.read_csv(f'static/hsk/intermediate/HSK{hsk_level}_cat_raw.csv', index_col=False)
df_sent_cat = dfsent.merge(df_cat, on='chinese', how='left')
assert df_sent_cat['category'].isna().sum() == 0
df_sent_cat.to_csv(f'static/hsk/HSK{hsk_level}_sent_cat.csv', index=False)
df_sent_cat.sample(5)

,index,chinese,trad,hsk3.0_pinyin,hsk3.0_def,video_notes,pinyin,english,sentence,sentence_pinyin,sentence_english,category
754,754,爽,爽,shuǎng,comfortable,HSK3.0 definition: comfortable,shuǎng,pleasant,天气真爽,tiān qì zhēn shuǎng,The weather is pleasant,Qualities & Characteristics
308,308,高考,高考,gāokǎo,college entrance exam (especially as abbr. for...,HSK3.0 definition: college entrance exam (espe...,gāo kǎo,university entrance exam,学生准备高考,xué shēng zhǔn bèi gāo kǎo,Students are preparing for the university entr...,School & Education
853,853,为此,為此,wèicǐ,"for this reason, with regards to this, in this...","HSK3.0 definition: for this reason, with regar...",wèi cǐ,for this reason,他努力学习，为此取得好成绩,tā nǔ lì xué xí， wèi cǐ qǔ dé hǎo chéng jì,He studied hard and achieved good results for ...,Logic & Reasoning
214,214,地板,地板,dìbǎn,"boarding, planking, hatch, plat, floorboard, h...","HSK3.0 definition: boarding, planking, hatch, ...",dì bǎn,floor,地板需要打扫干净,dì bǎn xū yào dǎ sǎo gān jìng,The floor needs to be cleaned,Construction & Materials
672,672,全力,全力,quánlì,"all one's strength, wholehearted dedication","HSK3.0 definition: all one's strength, wholehe...",quán lì,full force,我们要全力以赴,wǒ men yào quán lì yǐ fù,We must go all out,Qualities & Characteristics

In [232]:
# Print out rows with more than 6 commas
with open(f'static/hsk/intermediate/HSK{hsk_level}_sent_raw.csv', 'r') as file:
    for i_line, line in enumerate(file):
        if i_line > 0:
            n_commas = line.count(',')
            if n_commas != 5:
                print(f"{n_commas}, line{i_line}: {line}")

# 5. update video slide settings

In [ ]:
# # Extra add
# video_number=10
# output_path = 'output/videos/'
# hanzi_font_path = '/System/Library/Fonts/STHeiti Medium.ttc'

# ####### Extra add above ##############################

# subtitle = {
#     'chinese': 'HSK2级音频卡片',
#     'pinyin': 'HSK2 jí yīnpín kǎpiàn',
#     'english': 'HSK2 audio flashcards'
#     }  # UPDATE ON NEW VIDEO
# nonvocab_slides = {
#     'intro': {
#         'chinese': f"欢迎观看我的普通话数据库视频 {video_number}: {subtitle['chinese']}",
#         'pinyin': f"Huānyíng guānkàn wǒ de pǔtōnghuà shùjùkù shìpín {video_number}: {subtitle['pinyin']}",
#         'english': f"Welcome to my Mandarin Chinese Database Video {video_number}: {subtitle['english']}",
#         'clip_index': 0,
#         'change_index': -2,
#         'pause_ms': 500,

#         'channel_title': ('My Mandarin Database', '我的普通话数据库'),
#         'video_number': (f'Video #{video_number}', f'视频#{video_number}'),
#         'video_name': (subtitle['english'], subtitle['chinese']),
#         'video_structure': ('English first, Chinese second\nExample Chinese sentences', '先英文，后中文\n并附中文例句'),
#         'count_str': ("{n_vocab_words} words", "{n_vocab_words}个词汇"),
#         'duration_str': ('{audio_duration_minutes:.0f} minutes', '{audio_duration_minutes:.0f}分钟'),
#         'feedback': ('If you have any questions, suggestions, or feedback\nplease leave a comment', '如果你有任何问题、建议或反馈\n请留言'),

#         'x_bias_english_side': 80,
#         'text_configs': [
#             {
#             'font_name': hanzi_font_path,
#             'font_size': 32,
#             'y': 100,
#             'spacing': 20,
#             'align': 'center',
#             'fill': "#000000",
#             },
#             {
#             'font_name': hanzi_font_path,
#             'font_size': 24,
#             'y': 300,
#             'spacing': 10,
#             'align': 'center',
#             'fill': "#555555",
#             },
#             ]
#     },

#     'word_list': {
#         'chinese_unfill': '这些是将在接下来的{audio_duration_minutes:.0f}分钟内复习的{n_vocab}个单词',
#         'pinyin_unfill': 'Zhèxiē shì jiàng zài jiē xiàlái de {audio_duration_minutes:.0f} fēnzhōng nèi fùxí de {n_vocab} gè dāncí',
#         'english_unfill': 'These are the {n_vocab} words that will be reviewed over the next {audio_duration_minutes:.0f} minutes',
#         'clip_index': 1,
#         'change_index': -1,
#         'pause_ms': 500,

#         'y_top': 10,
#         'y_bottom': 100,
#         'x_top': 10,
#         'spacing': 2,
#         'font_size': 10,
#         'fill': '#000000',
#         'align': 'left',
#         'col_space': 2,
#         'col_space_big': 4,
#         'definition_configs':{
#             'chinese': {'x_offset': 0, 'x_max': 30, 'font_path': hanzi_font_path},
#             'pinyin': {'x_offset': None, 'x_max': 44, 'font_path': hanzi_font_path},
#             'english': {'x_offset': None, 'x_max': 44, 'font_path': hanzi_font_path},
#         },
#     },

#     'outro': {
#         'chinese': '如果你有任何问题、建议或反馈，请留言。请点赞并订阅。',
#         'pinyin': 'Rúguǒ nǐ yǒu rènhé wèntí, jiànyì huò fǎnkuì, qǐng liúyán. Qǐng diǎn zàn bìng dìngyuè.',
#         'english': 'If you have any questions, suggestions, or feedback, please leave a comment. Please like and subscribe.',
#         'clip_index': -1,
#         'change_index': None,
#         'pause_ms': 500,


#         'y_top': 4,
#         'y_bottom': 80,
#         'x_top': 4,
#         'spacing': 1,
#         'font_size': 10,
#         'fill': '#000000',
#         'align': 'left',
#         'col_space': 1,
#         'col_space_big': 2,
#         'definition_configs':{
#             'chinese': {'x_offset': 0, 'x_max': 23, 'font_path': hanzi_font_path},
#             'pinyin': {'x_offset': None, 'x_max': 32, 'font_path': hanzi_font_path},
#             'english': {'x_offset': None, 'x_max': 39, 'font_path': hanzi_font_path},
#         },
#     }
# }

# subtitle_text_configs = {
#     'font_size': 20,
#     'font_name': hanzi_font_path,
#     'y': 640,
#     'spacing': 5,
#     'align': 'center',
#     'fill': "#000000",
# }

# ####### Extra add ##############################
# subtitle_text_configs['font'] = ImageFont.truetype(subtitle_text_configs['font_name'], subtitle_text_configs['font_size'])
# for nv_name, nv_settings in nonvocab_slides.items():
#     if 'chinese' not in nv_settings.keys():
#         nonvocab_slides[nv_name]['chinese'] = nv_settings['chinese_unfill'].format(**audio_filler_variables)
#         nonvocab_slides[nv_name]['pinyin'] = nv_settings['pinyin_unfill'].format(**audio_filler_variables)
#         nonvocab_slides[nv_name]['english'] = nv_settings['english_unfill'].format(**audio_filler_variables)
# for _, row in df_vocab_audio_durations.iterrows():
#     if not pd.isna(row['nonvocab_key']):
#         nonvocab_slides[row['nonvocab_key']]['duration'] = row['combined']
#         nonvocab_slides[row['nonvocab_key']]['start'] = row['start']

# 1. Overlay image on original icon

In [ ]:
from utils_video import overlay_one_image_on_another
project_artifacts_folder = 'videos/1001_ec_csent_hsk1_v1'
original_icon_path = f'{project_artifacts_folder}/icon.png'
mario_slide_path = f'{project_artifacts_folder}/chinese_cat.png'
new_image_path = f'{project_artifacts_folder}/icon_with_pic.png'
xy_offset = (-500, 0)

new_img = overlay_one_image_on_another(original_icon_path, mario_slide_path, xy_offset, new_image_path)
new_img.display_in_notebook()

# 2. Compare tts voices

In [ ]:
from edge_tts import list_voices
voices = await list_voices()
voices = sorted(voices, key=lambda voice: voice["ShortName"])
[x for x in voices if 'fil-PH' in x['Locale']]

[{'Name': 'Microsoft Server Speech Text to Speech Voice (af-ZA, AdriNeural)',
  'DisplayName': 'Adri',
  'LocalName': 'Adri',
  'ShortName': 'af-ZA-AdriNeural',
  'Gender': 'Female',
  'Locale': 'af-ZA',
  'LocaleName': 'Afrikaans (South Africa)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['Assistant', 'Narration'],
   'VoicePersonalities': ['Well-Rounded', 'Animated', 'Bright'],
   'ContentCategories': []},
  'WordsPerMinute': '147'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (af-ZA, WillemNeural)',
  'DisplayName': 'Willem',
  'LocalName': 'Willem',
  'ShortName': 'af-ZA-WillemNeural',
  'Gender': 'Male',
  'Locale': 'af-ZA',
  'LocaleName': 'Afrikaans (South Africa)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '155'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (am-ET, AmehaNeural)',
  'DisplayName': 'Ameha',
  'LocalName': 'አምሀ',
  'ShortName': 'am-ET-AmehaNeural',
  'Gender': 'Male',
  'Locale': 'am-ET',
  'LocaleName': 'Amharic (Ethiopia)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '112'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (am-ET, MekdesNeural)',
  'DisplayName': 'Mekdes',
  'LocalName': 'መቅደስ',
  'ShortName': 'am-ET-MekdesNeural',
  'Gender': 'Female',
  'Locale': 'am-ET',
  'LocaleName': 'Amharic (Ethiopia)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '117'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-AE, FatimaNeural)',
  'DisplayName': 'Fatima',
  'LocalName': 'فاطمة',
  'ShortName': 'ar-AE-FatimaNeural',
  'Gender': 'Female',
  'Locale': 'ar-AE',
  'LocaleName': 'Arabic (United Arab Emirates)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['News', 'E-learning'],
   'VoicePersonalities': ['Crisp', 'Bright', 'Clear'],
   'ContentCategories': []},
  'WordsPerMinute': '110'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-AE, HamdanNeural)',
  'DisplayName': 'Hamdan',
  'LocalName': 'حمدان',
  'ShortName': 'ar-AE-HamdanNeural',
  'Gender': 'Male',
  'Locale': 'ar-AE',
  'LocaleName': 'Arabic (United Arab Emirates)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '115'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-BH, AliNeural)',
  'DisplayName': 'Ali',
  'LocalName': 'علي',
  'ShortName': 'ar-BH-AliNeural',
  'Gender': 'Male',
  'Locale': 'ar-BH',
  'LocaleName': 'Arabic (Bahrain)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '121'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-BH, LailaNeural)',
  'DisplayName': 'Laila',
  'LocalName': 'ليلى',
  'ShortName': 'ar-BH-LailaNeural',
  'Gender': 'Female',
  'Locale': 'ar-BH',
  'LocaleName': 'Arabic (Bahrain)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '108'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-DZ, AminaNeural)',
  'DisplayName': 'Amina',
  'LocalName': 'أمينة',
  'ShortName': 'ar-DZ-AminaNeural',
  'Gender': 'Female',
  'Locale': 'ar-DZ',
  'LocaleName': 'Arabic (Algeria)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['News', 'E-learning'],
   'VoicePersonalities': ['Crisp', 'Bright', 'Clear'],
   'ContentCategories': []},
  'WordsPerMinute': '110'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-DZ, IsmaelNeural)',
  'DisplayName': 'Ismael',
  'LocalName': 'إسماعيل',
  'ShortName': 'ar-DZ-IsmaelNeural',
  'Gender': 'Male',
  'Locale': 'ar-DZ',
  'LocaleName': 'Arabic (Algeria)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '115'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-EG, SalmaNeural)',
  'DisplayName': 'Salma',
  'LocalName': 'سلمى',
  'ShortName': 'ar-EG-SalmaNeural',
  'Gender': 'Female',
  'Locale': 'ar-EG',
  'LocaleName': 'Arabic (Egypt)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['News', 'E-learning'],
   'VoicePersonalities': ['Crisp', 'Bright', 'Clear'],
   'ContentCategories': []},
  'WordsPerMinute': '103'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-EG, ShakirNeural)',
  'DisplayName': 'Shakir',
  'LocalName': 'شاكر',
  'ShortName': 'ar-EG-ShakirNeural',
  'Gender': 'Male',
  'Locale': 'ar-EG',
  'LocaleName': 'Arabic (Egypt)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '115'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-IQ, BasselNeural)',
  'DisplayName': 'Bassel',
  'LocalName': 'باسل',
  'ShortName': 'ar-IQ-BasselNeural',
  'Gender': 'Male',
  'Locale': 'ar-IQ',
  'LocaleName': 'Arabic (Iraq)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '113'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-IQ, RanaNeural)',
  'DisplayName': 'Rana',
  'LocalName': 'رنا',
  'ShortName': 'ar-IQ-RanaNeural',
  'Gender': 'Female',
  'Locale': 'ar-IQ',
  'LocaleName': 'Arabic (Iraq)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '98'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-JO, SanaNeural)',
  'DisplayName': 'Sana',
  'LocalName': 'سناء',
  'ShortName': 'ar-JO-SanaNeural',
  'Gender': 'Female',
  'Locale': 'ar-JO',
  'LocaleName': 'Arabic (Jordan)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '98'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-JO, TaimNeural)',
  'DisplayName': 'Taim',
  'LocalName': 'تيم',
  'ShortName': 'ar-JO-TaimNeural',
  'Gender': 'Male',
  'Locale': 'ar-JO',
  'LocaleName': 'Arabic (Jordan)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '113'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-KW, FahedNeural)',
  'DisplayName': 'Fahed',
  'LocalName': 'فهد',
  'ShortName': 'ar-KW-FahedNeural',
  'Gender': 'Male',
  'Locale': 'ar-KW',
  'LocaleName': 'Arabic (Kuwait)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '128'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-KW, NouraNeural)',
  'DisplayName': 'Noura',
  'LocalName': 'نورا',
  'ShortName': 'ar-KW-NouraNeural',
  'Gender': 'Female',
  'Locale': 'ar-KW',
  'LocaleName': 'Arabic (Kuwait)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['News', 'E-learning'],
   'VoicePersonalities': ['Crisp', 'Bright', 'Clear'],
   'ContentCategories': []},
  'WordsPerMinute': '121'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-LB, LaylaNeural)',
  'DisplayName': 'Layla',
  'LocalName': 'ليلى',
  'ShortName': 'ar-LB-LaylaNeural',
  'Gender': 'Female',
  'Locale': 'ar-LB',
  'LocaleName': 'Arabic (Lebanon)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '99'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-LB, RamiNeural)',
  'DisplayName': 'Rami',
  'LocalName': 'رامي',
  'ShortName': 'ar-LB-RamiNeural',
  'Gender': 'Male',
  'Locale': 'ar-LB',
  'LocaleName': 'Arabic (Lebanon)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '101'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-LY, ImanNeural)',
  'DisplayName': 'Iman',
  'LocalName': 'إيمان',
  'ShortName': 'ar-LY-ImanNeural',
  'Gender': 'Female',
  'Locale': 'ar-LY',
  'LocaleName': 'Arabic (Libya)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '108'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-LY, OmarNeural)',
  'DisplayName': 'Omar',
  'LocalName': 'أحمد',
  'ShortName': 'ar-LY-OmarNeural',
  'Gender': 'Male',
  'Locale': 'ar-LY',
  'LocaleName': 'Arabic (Libya)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '111'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-MA, JamalNeural)',
  'DisplayName': 'Jamal',
  'LocalName': 'جمال',
  'ShortName': 'ar-MA-JamalNeural',
  'Gender': 'Male',
  'Locale': 'ar-MA',
  'LocaleName': 'Arabic (Morocco)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '128'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-MA, MounaNeural)',
  'DisplayName': 'Mouna',
  'LocalName': 'منى',
  'ShortName': 'ar-MA-MounaNeural',
  'Gender': 'Female',
  'Locale': 'ar-MA',
  'LocaleName': 'Arabic (Morocco)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['News', 'E-learning'],
   'VoicePersonalities': ['Crisp', 'Bright', 'Clear'],
   'ContentCategories': []},
  'WordsPerMinute': '121'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-OM, AbdullahNeural)',
  'DisplayName': 'Abdullah',
  'LocalName': 'عبدالله',
  'ShortName': 'ar-OM-AbdullahNeural',
  'Gender': 'Male',
  'Locale': 'ar-OM',
  'LocaleName': 'Arabic (Oman)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '123'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-OM, AyshaNeural)',
  'DisplayName': 'Aysha',
  'LocalName': 'عائشة',
  'ShortName': 'ar-OM-AyshaNeural',
  'Gender': 'Female',
  'Locale': 'ar-OM',
  'LocaleName': 'Arabic (Oman)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['News', 'Assistant'],
   'VoicePersonalities': ['Sincere', 'Pleasant'],
   'ContentCategories': []},
  'WordsPerMinute': '118'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-QA, AmalNeural)',
  'DisplayName': 'Amal',
  'LocalName': 'أمل',
  'ShortName': 'ar-QA-AmalNeural',
  'Gender': 'Female',
  'Locale': 'ar-QA',
  'LocaleName': 'Arabic (Qatar)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '113'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-QA, MoazNeural)',
  'DisplayName': 'Moaz',
  'LocalName': 'معاذ',
  'ShortName': 'ar-QA-MoazNeural',
  'Gender': 'Male',
  'Locale': 'ar-QA',
  'LocaleName': 'Arabic (Qatar)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '114'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-SA, HamedNeural)',
  'DisplayName': 'Hamed',
  'LocalName': 'حامد',
  'ShortName': 'ar-SA-HamedNeural',
  'Gender': 'Male',
  'Locale': 'ar-SA',
  'LocaleName': 'Arabic (Saudi Arabia)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '107'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-SA, ZariyahNeural)',
  'DisplayName': 'Zariyah',
  'LocalName': 'زارية',
  'ShortName': 'ar-SA-ZariyahNeural',
  'Gender': 'Female',
  'Locale': 'ar-SA',
  'LocaleName': 'Arabic (Saudi Arabia)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['News', 'E-learning'],
   'VoicePersonalities': ['Crisp', 'Bright', 'Clear'],
   'ContentCategories': []},
  'WordsPerMinute': '105'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-SY, AmanyNeural)',
  'DisplayName': 'Amany',
  'LocalName': 'أماني',
  'ShortName': 'ar-SY-AmanyNeural',
  'Gender': 'Female',
  'Locale': 'ar-SY',
  'LocaleName': 'Arabic (Syria)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['News', 'Assistant'],
   'VoicePersonalities': ['Sincere', 'Pleasant'],
   'ContentCategories': []},
  'WordsPerMinute': '122'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-SY, LaithNeural)',
  'DisplayName': 'Laith',
  'LocalName': 'ليث',
  'ShortName': 'ar-SY-LaithNeural',
  'Gender': 'Male',
  'Locale': 'ar-SY',
  'LocaleName': 'Arabic (Syria)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '133'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-TN, HediNeural)',
  'DisplayName': 'Hedi',
  'LocalName': 'هادي',
  'ShortName': 'ar-TN-HediNeural',
  'Gender': 'Male',
  'Locale': 'ar-TN',
  'LocaleName': 'Arabic (Tunisia)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '118'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-TN, ReemNeural)',
  'DisplayName': 'Reem',
  'LocalName': 'ريم',
  'ShortName': 'ar-TN-ReemNeural',
  'Gender': 'Female',
  'Locale': 'ar-TN',
  'LocaleName': 'Arabic (Tunisia)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'TailoredScenarios': ['News', 'Assistant'],
   'VoicePersonalities': ['Sincere', 'Pleasant'],
   'ContentCategories': []},
  'WordsPerMinute': '112'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-YE, MaryamNeural)',
  'DisplayName': 'Maryam',
  'LocalName': 'مريم',
  'ShortName': 'ar-YE-MaryamNeural',
  'Gender': 'Female',
  'Locale': 'ar-YE',
  'LocaleName': 'Arabic (Yemen)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '108'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (ar-YE, SalehNeural)',
  'DisplayName': 'Saleh',
  'LocalName': 'صالح',
  'ShortName': 'ar-YE-SalehNeural',
  'Gender': 'Male',
  'Locale': 'ar-YE',
  'LocaleName': 'Arabic (Yemen)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '115'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (as-IN, PriyomNeural)',
  'DisplayName': 'Priyom',
  'LocalName': 'প্ৰিয়ম',
  'ShortName': 'as-IN-PriyomNeural',
  'Gender': 'Male',
  'Locale': 'as-IN',
  'LocaleName': 'Assamese (India)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []}},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (as-IN, YashicaNeural)',
  'DisplayName': 'Yashica',
  'LocalName': 'যাশিকা',
  'ShortName': 'as-IN-YashicaNeural',
  'Gender': 'Female',
  'Locale': 'as-IN',
  'LocaleName': 'Assamese (India)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []}},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (az-AZ, BabekNeural)',
  'DisplayName': 'Babek',
  'LocalName': 'Babək',
  'ShortName': 'az-AZ-BabekNeural',
  'Gender': 'Male',
  'Locale': 'az-AZ',
  'LocaleName': 'Azerbaijani (Latin, Azerbaijan)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '114'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (az-AZ, BanuNeural)',
  'DisplayName': 'Banu',
  'LocalName': 'Banu',
  'ShortName': 'az-AZ-BanuNeural',
  'Gender': 'Female',
  'Locale': 'az-AZ',
  'LocaleName': 'Azerbaijani (Latin, Azerbaijan)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',
  'VoiceTag': {'ModelSeries': ['Monolingual'],
   'Source': ['Azure'],
   'ContentCategories': [],
   'VoicePersonalities': []},
  'WordsPerMinute': '114'},
 {'Name': 'Microsoft Server Speech Text to Speech Voice (bg-BG, BorislavNeural)',
  'DisplayName': 'Borislav',
  'LocalName': 'Борислав',
  'ShortName': 'bg-BG-BorislavNeural',
  'Gender': 'Male',
  'Locale': 'bg-BG',
  'LocaleName': 'Bulgarian (Bulgaria)',
  'SampleRateHertz': '48000',
  'VoiceType': 'Neural',
  'Status': 'GA',

In [20]:
# from edge_tts import list_voices
# voices = list_voices()
# voices = sorted(voices, key=lambda voice: voice["ShortName"])
from collections import defaultdict
dict_voice_list = defaultdict(list)
for voice in voices:
    dict_voice_list['name'].append(voice['ShortName'])
    dict_voice_list['language'].append(voice['ShortName'].split('-')[0])
    dict_voice_list['country'].append(voice['ShortName'].split('-')[1])
    dict_voice_list['gender'].append(voice['Gender'])
    dict_voice_list['content_categories'].append(", ".join(voice["VoiceTag"]["ContentCategories"]))
    dict_voice_list['personalities'].append(", ".join(voice["VoiceTag"]["VoicePersonalities"]))
df_voice_list = pd.DataFrame(dict_voice_list)
df_voice_list[df_voice_list['language']]
df_voice_list.head()

,name,language,country,gender,content_categories,personalities
0,af-ZA-AdriNeural,af,ZA,Female,,"Well-Rounded, Animated, Bright"
1,af-ZA-WillemNeural,af,ZA,Male,,
2,am-ET-AmehaNeural,am,ET,Male,,
3,am-ET-MekdesNeural,am,ET,Female,,
4,ar-AE-FatimaNeural,ar,AE,Female,,"Crisp, Bright, Clear"

In [26]:
# df_voice_list[df_voice_list['country']=='VN']

,name,language,country,gender,content_categories,personalities
504,vi-VN-HoaiMyNeural,vi,VN,Female,,
505,vi-VN-NamMinhNeural,vi,VN,Male,,

In [15]:
import pandas as pd
df = pd.read_csv('static/edge-tts_zh_options.csv')
df.head()

,Unnamed: 0,name,language,country,gender,content_categories,personalities
0,541,zh-CN-Xiaochen:DragonHDLatestNeural,zh,CN,Female,NaN,"Friendly, Casual, Upbeat"
1,542,zh-CN-XiaochenMultilingualNeural,zh,CN,Female,NaN,"Friendly, Casual, Upbeat"
2,543,zh-CN-XiaochenNeural,zh,CN,Female,NaN,"Friendly, Casual, Upbeat"
3,544,zh-CN-XiaohanNeural,zh,CN,Female,NaN,"Gentle, Warm, Emotional"
4,545,zh-CN-XiaomengNeural,zh,CN,Female,NaN,"Gentle, Upbeat, Friendly"

In [16]:
df['language'].value_counts()

language
zh    42
Name: count, dtype: int64

In [ ]:
from utils_audio import generate_example_recordings_from_all_edge_tts_voices
generate_example_recordings_from_all_edge_tts_voices(
    '靠近点，我想闻你身上的味道', 'zh', filter_gender=['Female'], filter_personality='Confident')
generate_example_recordings_from_all_edge_tts_voices(
    "Come closer, I want your scent", 'en', filter_gender=['Female'], filter_personality='Confident')

# 3. Leading space file problems

In [69]:
# Fix some leading space problems
import os
import glob
# all_audio_files = glob.glob('output/tts/en-US-AvaMultilingualNeural/*')
all_audio_files = glob.glob('output/tts/zh-CN-XiaoyuMultilingualNeural/*')
print(len(all_audio_files), all_audio_files[:3])
for i_file, audio_file in enumerate(all_audio_files):
    if audio_file.split('/')[-1][0] == ' ':
        new_audio_file = '/'.join(audio_file.split('/')[:-1]) + '/' + audio_file.split('/')[-1].strip()
        os.rename(audio_file, new_audio_file)
        print(audio_file)
        print(new_audio_file)
    else:
        print(f'do not rename {audio_file}')

2442 ['output/tts/zh-CN-XiaoyuMultilingualNeural/脸.mp3', 'output/tts/zh-CN-XiaoyuMultilingualNeural/今后我要努力学习.mp3', 'output/tts/zh-CN-XiaoyuMultilingualNeural/安静.mp3']
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/脸.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/今后我要努力学习.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/安静.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/它们是我朋友的书。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/大学.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/车票.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 商店在银行前边.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/商店在银行前边.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/得到.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/体育.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/要.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 桌子在房间中间.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/桌子在房间中间.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 商店在那边.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/商店在那边.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/学校要举行运动会.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/开玩笑.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这部电影真好看.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这部电影真好看.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/今天见到你很高兴.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我发现了一家好餐馆.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我发现了一家好餐馆.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/外国.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/喂.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/对.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/瓶.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/边.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 他是高中生.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/他是高中生.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我有三本书.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我有三本书.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/可是.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/味道.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/和.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/响.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/换个角度看问题.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/背.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/公里.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/教学楼.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/南.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/打电话.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 老师在黑板上写字.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/老师在黑板上写字.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这件衣服太贵了.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这件衣服太贵了.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/奶奶.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/高级.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/书包.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/球队.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我有两个妹妹.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 她的声音很好听.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/她的声音很好听.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/放学.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 他买了大量的书.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/他买了大量的书.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/停车.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我家没有网。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/该.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/今天太阳很大。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/请问.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 她喜欢画画.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/她喜欢画画.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/你什么时候有空儿？.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/凉.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/帮忙.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/为.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/公司通知我们下周开会。.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我有四个苹果.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我有四个苹果.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/中.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我在学校.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我在学校.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/他先写作业，接着去玩.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 下课后我们去打球.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/下课后我们去打球.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我闻到花的香味。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/如果.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 她答应帮我.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/她答应帮我.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我们早上七点出发.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我们早上七点出发.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/别的.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/称.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/黑板.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/生日.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/地铁的入口在超市旁边。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/门口.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/错.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这本书我看过两遍.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这本书我看过两遍.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/怎样.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我用电脑写作业.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/湖.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/关.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/大.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/请坐.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/老师.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/成为.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/走.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我喜欢做饭.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我喜欢做饭.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/篮球.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/百.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/他.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/瓶子.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我打算明天去旅行.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我打算明天去旅行.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/间.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/越.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我家有五口人.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 那是我的书.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/那是我的书.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我在三年级.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/越来越.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/的.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/慢.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/他们在打排球.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我们去参观工厂.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我们去参观工厂.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 没关系我可以等.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/没关系我可以等.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/回国.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 中国的南方很热.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/中国的南方很热.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 他是谁.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/他是谁.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 银行在学校左边.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/银行在学校左边.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/讲.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我跟朋友去看电影.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我跟朋友去看电影.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/午饭.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/碰到.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/爱情.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/只要.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/他上课老是迟到.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/公路.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我哥哥明年要出国.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我哥哥明年要出国.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/这个网站很有用。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我接到了一封信.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/妈妈对我说“晚安”。.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我家里有三口人.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我家里有三口人.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/你一定能成功。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/玩儿.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 妈妈很关心我.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/妈妈很关心我.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/重视.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/卖.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/北.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我晚上十点睡觉.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我晚上十点睡觉.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/市长.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/十.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/这家店卖水果.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/去.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/分开.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 蛋糕吃了一半.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/蛋糕吃了一半.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/例如.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/前年.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/计划.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我有两个妹妹.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我有两个妹妹.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/特别.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/放.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/这本书里有很多漂亮的图片。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/今年.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/流行.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 那些中学生在操场运动.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/那些中学生在操场运动.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/请客.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/年轻.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/见.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我用银行卡取钱。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/正确.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我喜欢听音乐。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/随时.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/酒.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/房间.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/谢谢.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/这时候.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我在电视上看新闻。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/现在三点了.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/手.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/以后我要更加努力。.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我每天七点起床.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我每天七点起床.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/米饭.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/他心中有一个梦想。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/网上.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/一定.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/加.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/好吃.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/里边.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/全家.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我前天去北京了.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我前天去北京了.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/你对这件事有什么意见吗？.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/挺好.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/上边.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/前.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 天黑了.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/天黑了.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/早起是一个好习惯。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/出租车.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/全部.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/他在学习计算机科学.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/桌上有一个水瓶子.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/吃太多糖有坏处.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/心里.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/接下来我们要做什么？.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 她是女医生.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/她是女医生.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/晚餐.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/他喜欢黄色的花.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这些苹果很新鲜.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这些苹果很新鲜.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/放心.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/第.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/起床.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/呢.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这家饭店的服务很好.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这家饭店的服务很好.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/体育馆.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/她昨天剪了头发。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/大量.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我有九个朋友.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我有九个朋友.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我的女朋友喜欢看电影.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我的女朋友喜欢看电影.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/人口.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/千.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 他脸红了.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/他脸红了.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/这道菜的味道很好。.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 他是球队的队长.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/他是球队的队长.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/晚报.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/算.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/推.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/网友.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 多么美丽的风景啊.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/多么美丽的风景啊.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/拿出.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/她对客人很热情.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/阴天.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我们明天去北京.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我们明天去北京.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这道题的分数是零.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这道题的分数是零.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 我有五个苹果.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/我有五个苹果.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/地图.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/右边.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/请阅读以下内容。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/他很常迟到.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/明天.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这段话很有意思.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这段话很有意思.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/外卖.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 他刚刚离开.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/他刚刚离开.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/你为什么不来上课？.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/记.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 今天气温很低.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/今天气温很低.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 你学习中文多久了.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/你学习中文多久了.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 学校在城市的西边.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/学校在城市的西边.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/以下.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/快要.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这个学习方法很有效.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这个学习方法很有效.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 道路两边有树.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/道路两边有树.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 她家有一个大花园.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/她家有一个大花园.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/中小学学生放暑假了。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/也许.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 他每天早上跑步.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/他每天早上跑步.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/重点.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/女.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/北边.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/欢迎你来我家.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/这里有一百本书.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/请把药水摇一摇再喝。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/今天的气温很高.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 她的男朋友很高.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/她的男朋友很高.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/出院.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/快餐.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/行人.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 下雨的话我就不去.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/下雨的话我就不去.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/课本.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我听说他要结婚了。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/国.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/那时候我住在北京.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我从学校走回家.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这个手机坏了.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这个手机坏了.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/希望你一路顺风。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/不但.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这里的车辆很多.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这里的车辆很多.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/老师在检查作业.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/以外.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/五.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/白.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 这是一段有趣的对话.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/这是一段有趣的对话.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/我是前年来的.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/你的答案错了.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/所以.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/以上.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/跟.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 他坐下喝水.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/他坐下喝水.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/快递已经送到公司了。.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/今天比昨天冷.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/星期天.mp3
do not rename output/tts/zh-CN-XiaoyuMultilingualNeural/你今天过得怎么样？.mp3
output/tts/zh-CN-XiaoyuMultilingualNeural/ 水果在盒子里.mp3

# 7. Add hsk column to google sheet

In [60]:
import pandas as pd
with open('static/mmd_url.txt', 'r') as file:
    sheet_url = file.read()
sheet_url = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')
df = pd.read_csv(sheet_url).sort_values('id')
df.head()

,id,chinese,pinyin,english,type,priority,known,known_pinyin_prompt,known_english_prompt,cat_v3,...,aji_label,category1,category2,category_gpt,video_notes,notes,hsk_level,voice_zh,voice_en,reverse chinese
0,1,房贷,fáng dài,mortgage,word,1.0,1.0,1.0,2.0,Finance & Economy,...,NaN,life,NaN,NaN,NaN,NaN,NONE,NaN,NaN,贷房
1,2,白天,bái tiān,daytime,word,2.0,2.0,1.0,1.0,Time,...,NaN,time,NaN,NaN,NaN,NaN,1,NaN,NaN,天白
2,3,组成,zǔ chéng,to form;make up,word,3.0,5.0,5.0,5.0,Language & Expression,...,NaN,general,NaN,NaN,NaN,NaN,2,NaN,NaN,成组
3,4,组合,zǔ hé,combination,word,1.0,5.0,3.0,2.0,Work & Career,...,NaN,general,NaN,NaN,NaN,NaN,3,NaN,NaN,合组
4,5,保险,bǎo xiǎn,insurance,word,1.0,1.0,1.0,2.0,Finance & Economy,...,NaN,life,NaN,NaN,NaN,NaN,3,NaN,NaN,险保

In [6]:
# Import HSK words and save into their own combined csv
if False:
    hsk_raw_files = sorted(glob.glob('static/hsk/HSK*.tsv'))
    dfs_all = []
    for hsk_file in hsk_raw_files:
        df_tmp = pd.read_csv(hsk_file, delimiter='\t', header=None).rename(columns={0:'trad', 1:'chinese', 2:'hsk3.0_pinyin', 3: 'hsk3.0_def'})
        df_tmp['hsk_level'] = hsk_file.split(' ')[-1][:-4]
        dfs_all.append(df_tmp)
    df_all_hsk = pd.concat(dfs_all).reset_index(drop=True)
    df_all_hsk.to_csv('static/hsk/hsk_1to9.csv')
else:
    df_all_hsk = pd.read_csv('static/hsk/hsk_1to9.csv', index_col=0)
print(len(df_all_hsk))
df_all_hsk.head()

11036

,trad,chinese,hsk3.0_pinyin,hsk3.0_def,hsk_level
0,愛,爱,ài,"love, like, be fond of, be keen on, cherish, b...",1
1,愛好,爱好,àihào,"love, like, be fond of, be keen on",1
2,爸爸,爸爸,bàba,"old man, father, papa, pappa, daddy, pa, beget...",1
3,白,白,bái,"white, clear, pure, plain, wrongly written/mis...",1
4,八,八,bā,det.: eight,1

In [9]:
# Drop duplicates for hsk
df_all_hsk_nodup = df_all_hsk.drop_duplicates('chinese')[['chinese', 'hsk_level']]
df_mmd_hsklevels = df[['id', 'chinese']].merge(df_all_hsk_nodup, on='chinese', how='left').fillna('NONE')
df_mmd_hsklevels.to_csv('static/hsk/mmd_hsk_20251020.csv')
df_mmd_hsklevels[['hsk_level']].to_csv('static/hsk/mmd_hsk_20251020_tmp.csv', index=False)

# Convert semicolon csv to csv
news stories

In [1]:
import pandas as pd
file_name = '20251212_travel'
file_target_folder = 'lists'
df_tmp = pd.read_csv(f'static/texts/raw/{file_name}.csv', delimiter=';;')
# df_tmp = pd.read_csv(f'static/texts/raw/{file_name}.tsv', delimiter='\t')
df_tmp.reset_index(inplace=True)
for col in df_tmp.columns:
    if col != 'index':
        df_tmp[col] = df_tmp[col].str.replace(',','，').str.replace('/','\\')
df_tmp.to_csv(f'static/texts/{file_target_folder}/{file_name}.csv', index=False)

/var/folders/z8/s7_mn6894xd5kj7pdpx6t6100000gn/T/ipykernel_15243/2558091732.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_tmp = pd.read_csv(f'static/texts/raw/{file_name}.csv', delimiter=';;')

# Most common characters

In [1]:
from collections import defaultdict
import pandas as pd
from constants import WORD_TYPES, PROPER_NOUN_TYPES
df_all_vocab = pd.read_csv('static/latest_data.csv')
df_all_vocab = df_all_vocab[
    (df_all_vocab['type'].isin(WORD_TYPES + PROPER_NOUN_TYPES)) &
    (df_all_vocab['priority'] <= 4) &
    (df_all_vocab['adu'] >= 3) &
    (df_all_vocab['per'] >= 3)
    ].reset_index(drop=True)
print(len(df_all_vocab))
df_all_vocab.head()

2886

,id,chinese,pinyin,english,type,priority,category1,category2,cat_v3,cat2_v3,...,sentence_pinyin,sentence_english,date,source1,source2,funny,per,adu,slang,phonetic
0,160,袋鼠,dài shǔ,kangaroo,word,3.0,animal,zoo,Animals,NaN,...,ào dà lì yà yǒu hěn duō dài shǔ,there are many kangaroos in Australia,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
1,161,松鼠,sōng shǔ,squirrel,word,3.0,animal,wild,Animals,NaN,...,sōng shǔ zài shù shàng tiào lái tiào qù,the squirrel jumps around in the tree,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
2,168,长颈鹿,cháng jǐng lù,giraffe,word,2.0,animal,zoo,Animals,NaN,...,Dòngwùyuán yǒu chángjǐnglù,There are giraffes in the zoo,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
3,170,龙虾,lóng xiā,lobster,word,2.0,animal,sea,Animals,NaN,...,Tāmen diǎn le yī zhī lóngxiā dāng wǎncān,They ordered a lobster for dinner,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
4,173,恐龙,kǒng lóng,dinosaur,word,2.0,animal,zoo,Animals,NaN,...,Kǒnglóng zǎo yǐ zài dìqiú shàng mièjué,Dinosaurs have long been extinct on Earth,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN

In [12]:
from collections import defaultdict
import pandas as pd
from constants import WORD_TYPES, PROPER_NOUN_TYPES

def get_filtered_words(df_all_vocab, shared_char, max_priority, min_adu, min_per, types_allowed, sort_cols=['priority', 'cat_v3', 'pinyin'], sort_ascending=[True, True, True]):
    if shared_char is None:
        df_filtered = df_all_vocab[
            (df_all_vocab['type'].isin(types_allowed)) &
            (df_all_vocab['priority'] <= max_priority) &
            (~(df_all_vocab['adu'] < min_adu)) &
            (~(df_all_vocab['per'] < min_per))
        ].sort_values(by=sort_cols, ascending=sort_ascending).reset_index(drop=True)
        return df_filtered
    else:
        df_filtered = df_all_vocab[
            (df_all_vocab['chinese'].str.contains(shared_char)) &
            (df_all_vocab['type'].isin(types_allowed)) &
            (df_all_vocab['priority'] <= max_priority) &
            (~(df_all_vocab['adu'] < min_adu)) &
            (~(df_all_vocab['per'] < min_per))
        ].sort_values(sort_cols, ascending=sort_ascending).reset_index(drop=True)
        return df_filtered

shared_char = '车'
max_priority = 3
min_adu = 3
min_per = 3
types_allowed = WORD_TYPES + PROPER_NOUN_TYPES

df_all_vocab = pd.read_csv('static/latest_data.csv')
df_filtered = get_filtered_words(df_all_vocab, shared_char, max_priority, min_adu, min_per, types_allowed)
print(len(df_filtered))
df_filtered.head()

23

,id,chinese,pinyin,english,type,priority,category1,category2,cat_v3,cat2_v3,...,sentence_pinyin,sentence_english,date,source1,source2,funny,per,adu,slang,phonetic
0,426,出租车,chū zū chē,taxi,word,1.0,travel,NaN,Transportation,NaN,...,tā dǎ le yī liàng chū zū chē,he took a taxi,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
1,427,电动车,diàn dòng chē,electric vehicle,word,1.0,travel,NaN,Transportation,NaN,...,tā mǎi le yī liàng diàn dòng chē,he bought an electric scooter,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
2,1249,堵车,dǔ chē,traffic jam,word,1.0,travel,NaN,Transportation,NaN,...,Wǒmen zài gāosù gōnglù shàng dǔchē le,We got stuck in traffic on the highway,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
3,425,公共汽车,gōng gòng qì chē,bus,word,1.0,travel,NaN,Transportation,NaN,...,wǒ men zuò gōng gòng qì chē qù shì zhōng xīn,we took a bus to the city center,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
4,395,火车,huǒ chē,train,word,1.0,travel,NaN,Transportation,NaN,...,tā men zuò huǒ chē qù běi jīng,they took the train to Beijing,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN

In [ ]:
def get_filtered_words(df_all_vocab, shared_char, max_priority, min_adu, min_per, types_allowed, sort_cols=['priority', 'cat_v3', 'pinyin'], sort_ascending=[True, True, True]):
    if shared_char is None:
        df_filtered = df_all_vocab[
            (df_all_vocab['type'].isin(types_allowed)) &
            (df_all_vocab['priority'] <= max_priority) &
            (~(df_all_vocab['adu'] < min_adu)) &
            (~(df_all_vocab['per'] < min_per))
        ].sort_values(by=sort_cols, ascending=sort_ascending).reset_index(drop=True)
        return df_filtered
    else:
        df_filtered = df_all_vocab[
            (df_all_vocab['chinese'].str.contains(shared_char)) &
            (df_all_vocab['type'].isin(types_allowed)) &
            (df_all_vocab['priority'] <= max_priority) &
            (~(df_all_vocab['adu'] < min_adu)) &
            (~(df_all_vocab['per'] < min_per))
        ].sort_values(sort_cols, ascending=sort_ascending).reset_index(drop=True)
        return df_filtered

7489 6554

character
子    53
人    44
大    44
机    33
电    28
心    26
地    26
口    26
时    25
国    25
小    25
语    25
省    25
一    24
公    24
花    23
中    23
不    23
车    23
自    23
Name: count, dtype: int64

In [54]:
','.join(df_character_appearances['character'].value_counts().index)

'人,子,大,机,不,心,电,自,地,车,口,时,水,生,手,花,公,家,中,可,科,主,体,国,发,小,头,信,动,气,外,一,猫,情,点,平,工,度,好,菜,行,的,期,成,物,下,间,名,器,到,话,学,重,分,毛,说,马,性,高,面,病,者,保,打,天,拉,出,金,球,流,火,香,单,装,有,果,加,线,品,作,开,多,客,语,法,长,排,理,日,义,用,标,明,身,台,合,美,海,前,率,化,上,包,业,安,同,红,看,文,豆,场,特,难,角,区,三,会,通,油,感,音,程,清,号,定,内,店,象,米,本,无,意,爱,游,乐,空,西,产,对,道,路,词,关,过,新,力,能,表,风,正,个,老,方,皮,量,女,论,友,教,板,斯,药,收,调,衣,脑,员,社,麻,实,师,书,别,带,提,裤,于,常,神,热,件,克,治,洗,年,基,事,商,住,优,鱼,处,房,婚,十,视,网,创,牛,记,瓜,里,观,室,传,言,具,计,代,证,料,回,直,布,酒,鼠,订,便,二,沙,周,报,糖,食,习,战,血,交,男,黄,利,礼,鸡,月,吃,受,相,饼,知,眼,白,南,毒,退,宝,赛,图,星,得,预,放,害,持,转,全,睡,伤,色,双,耳,导,先,百,库,声,夜,活,结,历,价,喜,育,未,纪,队,起,经,干,设,租,算,滑,箱,假,松,共,茶,光,东,目,肉,术,字,冰,掉,消,选,门,灯,费,应,数,银,后,形,巴,容,维,验,团,炸,随,圈,熟,制,序,式,印,惯,脸,死,诊,钱,比,卡,院,浪,反,项,压,零,节,入,差,楼,雪,走,片,界,恋,位,易,当,桌,六,尔,等,接,考,哥,票,立,私,系,了,户,龙,飞,统,货,支,认,码,剧,哈,确,微,山,想,政,迷,世,来,部,夫,牙,味,德,根,盘,完,冲,士,升,棉,现,博,貌,签,青,楚,初,跑,最,约,袋,咖,币,解,指,非,失,所,普,几,争,题,烦,志,奖,轮,源,纸,见,园,检,资,满,其,疫,管,和,条,杯,评,少,牌,整,汽,问,然,控,儿,木,堂,餐,速,达,告,模,尿,吐,负,危,深,企,民,农,鬼,港,独,锁,态,简,精,录,原,近,座,试,圾,泡,求,顺,冷,黑,领,亲,妈,值,低,凉,听,服,贴,思,妇,爆,免,航,缺,步,待,议,请,质,垃,戏,摩,旬,警,硬,孕,命,份,胡,查,肥,城,编,推,笔,华,醒,彩,卫,念,懂,笑,吸,投,着,厨,乌,啡,短,槽,暴,去,司,羊,造,律,恐,巾,弹,错,付,译,格,强,坏,铁,没,替,默,断,湿,引,总,石,亚,腿,草,镜,骗,累,腐,密,索,土,罗,配,酱,蜜,软,办,党,墨,阴,脚,虫,稳,露,偶,刀,写,停,觉,读,修,京,乎,套,军,晕,梯,影,息,屎,备,族,闻,频,垫,进,脏,取,居,准,职,链,泳,插,针,汗,拍,灵,急,连,种,补,遥,买,罪,类,瓦,股,衬,善,额,苗,净,闲,染,棍,弄,街,云,抱,纹,奶,击,霉,览,洞,射,限,列,效,联,层,恶,胖,减,狂,存,蒙,医,饭,功,衫,舍,床,介,怀,北,疑,够,之,波,迪,供,阳,输,换,变,至,锅,市,掌,乡,喷,症,塔,更,研,晒,防,闪,伦,抽,终,奥,狗,鼻,甜,丸,偏,画,卖,孔,必,肤,以,摄, ,钟,侣,余,候,超,售,蛋,增,登,芝,落,焦,务,液,概,毫,括,冻,型,享,运,首,据,助,激,测,脱,烧,背,景,省,伴,倒,休,鞋,广,演,固,坡,烘,轻,拖,照,快,架,吵,晚,今,肚,识,顾,困,弱,灰,惊,李,由,母,池,幕,爪,旅,边,熊,宽,破,偷,厅,朝,像,卷,饮,级,复,杂,瓶,留,离,虑,嘴,护,枪,半,汉,堡,示,险,王,闭,羽,笼,萝,异,烟,奇,样,树,邮,良,兰,班,极,按,薯,阶,扇,聊,春,向,拿,杀,细,环,柜,温,因,参,英,圣,万,紧,众,靠,梦,胃,舞,脆,\u200b,菠,烈,兵,玛,躁,淡,启,摊,探,屏,姓,挑,截,榴,延,担,1,耐,婿,胀,纳,详,谢,张,扔,络,贸,壳,芬,诈,厌,释,莲,规,为,站,追,莓,窝,腋,膨,宗,洋,番,鸟,罐,缆,痒,枕,醉,勇,章,练,喵,馆,骨,使,猪,鹅,守,他,污,隐,康,裁,荷,键,棒,砂,森,厕,林,端,姆,酪,滴,毯,尚,浴,就,谋,圆,芦,盒,钉,哔,裸,销,塑,哩,粮,坑,傻,屋,找,饿,勤,奋,缀,罚,疗,栗,闹,豚,坐,欧,笨,曼,真,秘,乱,况,虾,顿,须,雾,展,寨,胜,州,八,菲,始,望,越,府,舔,碑,雅,竞,令,欢,拜,丁,吓,虚,逊,谦,材,询,央,决,才,购,托,递,愿,洛,叉,坚,郊,蚊,迟,置,塞,埃,此,冠,把,仇,富,建,烂,惠,玻,鲜,魂,唐,宅,洲,璃,摇,盟,妻,集,积,择,底,扶,胎,坦,朗,许,尼,狼,尊,麦,怪,俄,藏,盖,澳,屁,艺,史,典,蔬,菇,龟,鹰,蚂,潜,局,氏,突,废,鸦,素,触,段,太,刷,膏,焙,五,诉,慕,仰,如,苦,暂,幻,执,驾,赌,构,改,涂,饱,刻,施,泌,渡,仔,腔,组,擦,尾,依,漏,椅,避,撒,承,势,脾,慢,做,丢,核,眠,误,忍,武,惧,泥,适,棋,即,江,幸,妹,播,骑,蒂,故,税,扭,淘,疼,次,缩,饰,讲,账,聚,烤,亿,任,则,逐,邻,扣,峰,早,官,技,养,卑,降,粗,督,再,佛,暗,舱,千,移,课,聘,显,健,绕,已,页,需,辑,紫,叹,第,逗,翻,融,肠,歌,押,辩,谈,违,临,充,往,姐,智,似,雨,围,耗,状,判,丛,鼓,障,季,幽,校,喉,盲,句,歧,丑,钢,痣,甚,奔,磨,舟,盆,琴,叛,橡,泽,抓,斑,杰,丝,剩,碰,渐,贬,畜,抚,患,邓,蜂,挣,虹,谱,扎,铝,枝,催,袜,悉,豪,振,刺,疮,哪,衡,剑,凳,隆,杆,摸,驼,仆,咪,迎,与,肩,尘,膀,姿,馍,茬,韭,胞,娘,归,庸,疯,梳,斗,潮,搬,霸,诞,宣,沉,瘾,欠,熨,妥,协,嗝,昆,枣,兔,炒,叫,蹭,足,胶,蕉,澡,伸,舌,涕,雷,借,尸,僵,溪,敢,乏,磁,薄,砖,兽,霾,吾,噜,伞,际,诺,趟,呼,畔,疲,弗,屑,浏,旋,湖,刮,P,冬,绝,鸭,炉,甲,估,赁,扫,帚,招,瑜,伽,屉,群,鄙,仿,桶,詹,袖,惫,侠,疙,瘩,逃,筷,挡,筒,仪,氛,捞,惕,卓,婆,润,岛,侬,汇,忙,谓,丽,葫,卤,岩,攀,穿,灭,摔,栈,储,涤,猜,纶,送,藕,伪,夸,骰,谣,宜,沃,瘤,劳,肯,瑞,肿,C,O,咙,S,-,T,7,肾,A,吉,娜,莎,趋,阿,陷,伙,阱,略,臣,蘑,辐,捷,屈,径,碧,琪,黛,蹄,蔓,讽,阪,止,燃,敦,吧,谷,·,莫,纽,啤,颠,盛,咒,诅,咚,奏,携,孩,隔,黎,兴,茫,臭,姚,秩,齿,灸,艇,奈,织,拼,抖,纺,副,蚱,鲸,叶,窄,隧,么,祈,祷,垄,繁,途,伺,蚁,券,玩,鼾,绒,暖,我,凡,碍,蝴,蝶,柠,戒,叮,雀,冥,秒,侦,搂,款,逻,偎,啰,檬,拥,蜷,粘,浣,仙,契,岁,矛,盾,述,尽,葵,午,秋,扁,远,嫉,粉,蓝,策,嘻,陌,都,缘,旗,尤,浆,糙,腰,励,箭,抬,答,救,村,阅,韵,堵,灌,宵,罩,著,败,野,例,冒,悲,监,互,是,妒,刚,罄,析,酸,妆,匹,茄,厘,谊,幺,怜,唯,甘,噱,惑,慰,宿,寂,寞,封,楂,批,兼,橙,桃,丹,胳,膊,趾,咳,嗽,脂,肪,碳,笋,皂,椒,萄,只,沐,葡,嘲,寓,俗,乳,內,左,抹,挞,竹,川,菌,各,庭,权,谅,柴,厂,返,匙,裔,遗,邪,悔,搞,雄,营,在,域,忽,辛,征,将,柔,痰,壶,熬,贵,漱,萃,专,末,载,被,浓,犬,痛,陆,距,噩,匿,怕,惜,钥,曲,傲,从,淤,漠,蒜,霜,贷,础,忘,吻,宠,债,娇,荫,铃,吹,绿,绵,右,馅,煎,痘,弃,另,虎,境,灾,毕,哲,渣,轨,唱,革,敏,察,震,划,帅,四,称,巨,泉,廊,乘,折,剔,捂,爽,透,弯,也,或,芋,羞,桥,元,旦,抢,很,劫,浮,钓,块,船,桂,糊,跳,丰,获,烛,蜡,忆,洁,咨,泼,孝,授,剂,锻,炼,绪,俱,牵,附,徒,骚,扰,耍,酷,姨,腻,仓,寄,搜,苍,址,珠,浙,沪,筛,纯,墙,羡,纤,蝇,翁,井,窗,帘,派,蟹,谐,梗,疱,茧,淋,蹲,踝,绳,粥,癌,某,桑,葚,培,训,邀,蝙,蝠,肺,碱,槛,宇,宙,申,赞,漂,混,寻,铺,丧,嚏,贿,赂,赶,辨,采,访,谍,蛙,谎,究,馈,祸,柿,福,垂,玉,腊,犯,希,湾,慎,谨,谚,讨,敌,辜,暑,暧,昧,刊,喻,晶,滩,藻,稽,瀑,禁,忌,稀,糯,绊,卜,蜗,僚,彼,帖,厦,泛,滥,济,注,要,严,牢,秀,惩,怨,辞,孤,钠,勺,驶,辈,杉,矶,填,恼,媒,躺,颈,赚,般,馄,饨,辣,荐,柳,摆,戴,河,古,伊,萨,挝,宾,柬,埔,植,鹿,苹'

# Create hsk1-6 file of processed

In [69]:
import glob
csv_names = sorted(glob.glob('static/hsk/HSK*_sent*.csv'))
cols_keep = ['chinese', 'pinyin', 'english', 'sentence', 'sentence_pinyin', 'sentence_english', 'hsk3.0_def', 'video_notes']
individual_dfs = []
for csv_name in csv_names:
    df_tmp = pd.read_csv(csv_name)[cols_keep]
    df_tmp['hsk_level'] = csv_name.split('HSK')[1][0]
    individual_dfs.append(df_tmp)
df_hsk1to6 = pd.concat(individual_dfs).reset_index(drop=True).reset_index()
df_hsk1to6.to_csv('static/hsk/hsk_1to6_sent.csv', index=False)
df_hsk1to6.head()

,index,chinese,pinyin,english,sentence,sentence_pinyin,sentence_english,hsk3.0_def,video_notes,hsk_level
0,0,爱,ài,love,我爱我的家人,wǒ ài wǒ de jiā rén,I love my family,"love, like, be fond of, be keen on, cherish, b...","HSK3.0 definition: love, like, be fond of, be ...",1
1,1,爱好,ài hào,hobby,她的爱好是唱歌,tā de ài hào shì chàng gē,her hobby is singing,"love, like, be fond of, be keen on",NaN,1
2,2,爸爸,bà ba,dad,爸爸每天送我去学校,bà ba měi tiān sòng wǒ qù xué xiào,my dad takes me to school every day,"old man, father, papa, pappa, daddy, pa, beget...","HSK3.0 definition: old man, father, papa, papp...",1
3,3,白,bái,white,这件衣服是白颜色的,zhè jiàn yī fú shì bái yán sè de,this piece of clothing is white,"white, clear, pure, plain, wrongly written/mis...","HSK3.0 definition: white, clear, pure, plain, ...",1
4,4,八,bā,eight,我家有八口人,wǒ jiā yǒu bā kǒu rén,there are eight people in my family,det.: eight,HSK3.0 definition: det.: eight,1

# create df for shared characters

In [73]:
df_all_hsk = pd.read_csv('static/hsk/hsk_1to6_sent.csv', index_col=0)
df_all_hsk

,chinese,pinyin,english,sentence,sentence_pinyin,sentence_english,hsk3.0_def,video_notes,hsk_level
index,,,,,,,,,
0,爱,ài,love,我爱我的家人,wǒ ài wǒ de jiā rén,I love my family,"love, like, be fond of, be keen on, cherish, b...","HSK3.0 definition: love, like, be fond of, be ...",1
1,爱好,ài hào,hobby,她的爱好是唱歌,tā de ài hào shì chàng gē,her hobby is singing,"love, like, be fond of, be keen on",NaN,1
2,爸爸,bà ba,dad,爸爸每天送我去学校,bà ba měi tiān sòng wǒ qù xué xiào,my dad takes me to school every day,"old man, father, papa, pappa, daddy, pa, beget...","HSK3.0 definition: old man, father, papa, papp...",1
3,白,bái,white,这件衣服是白颜色的,zhè jiàn yī fú shì bái yán sè de,this piece of clothing is white,"white, clear, pure, plain, wrongly written/mis...","HSK3.0 definition: white, clear, pure, plain, ...",1
4,八,bā,eight,我家有八口人,wǒ jiā yǒu bā kǒu rén,there are eight people in my family,det.: eight,HSK3.0 definition: det.: eight,1
...,...,...,...,...,...,...,...,...,...
5389,作,zuò,do/make,他每天作作业,tā měi tiān zuò zuò yè,He does homework every day,"do, make, rise, write, compose, pretend, affec...","HSK3.0 definition: do, make, rise, write, comp...",6
5390,最佳,zuì jiā,best,她是最佳选手,tā shì zuì jiā xuǎn shǒu,She is the best contestant,"first-rate, best, superlative, optimum","HSK3.0 definition: first-rate, best, superlati...",6
5391,作废,zuò fèi,void/invalid,票已经作废,piào yǐ jīng zuò fèi,The ticket is invalid,"to become invalid, to cancel, to delete, to nu...","HSK3.0 definition: to become invalid, to cance...",6
5392,座谈会,zuò tán huì,seminar,我们参加了座谈会,wǒ men cān jiā le zuò tán huì,We attended the seminar,"colloquium, symposiac, panel_discussion, an in...","HSK3.0 definition: colloquium, symposiac, pane...",6
5393,作战,zuò zhàn,combat,士兵准备作战,shì bīng zhǔn bèi zuò zhàn,The soldiers are preparing for combat,"do battle, war, fight, battle, conduct operations","HSK3.0 definition: do battle, war, fight, batt...",6

In [92]:
from collections import defaultdict
import pandas as pd
import os

def create_or_load_character_appearances():
    character_appearances_path = 'static/character_appearances.csv'
    if os.path.exists(character_appearances_path):
        print(f"Loading character appearances from {character_appearances_path}")
        df_character_appearances = pd.read_csv(character_appearances_path)
    else:
        print(f"Computing character appearances...")
        df_all_vocab = pd.read_csv('static/latest_data.csv')
        types_allowed = [
            'combo', 'proper noun', 'two word', 'suffix', 'no combo', 'prefix', 'single char', 'slang', 'abbreviation'
        ]
        cols_keep = ['chinese', 'pinyin', 'english', 'priority', 'hsk_level']
        df_all_vocab = df_all_vocab[
            (df_all_vocab['type'].isin(types_allowed)) & 
            (df_all_vocab['adu'] >= 3) &
            (df_all_vocab['per'] >= 3)
            ].reset_index(drop=True)
        df_all_vocab['hsk_level'] = None

        df_all_hsk = pd.read_csv('static/hsk/hsk_1to6_sent.csv', index_col=0)
        hsk_levels_allowed = [1, 2, 3, 4]
        df_all_hsk = df_all_hsk[df_all_hsk['hsk_level'].isin(hsk_levels_allowed)].reset_index(drop=True)
        df_all_hsk['priority'] = 4

        df_all = pd.concat([df_all_vocab[cols_keep], df_all_hsk[cols_keep]]).reset_index(drop=True)
        df_all = df_all.drop_duplicates(subset=['chinese']).reset_index(drop=True)

        dict_character_appearances = defaultdict(list)
        for _, row in df_all.iterrows():
            for char in row['chinese']:
                dict_character_appearances['character'].append(char)
                dict_character_appearances['word'].append(row['chinese'])
                dict_character_appearances['priority'].append(row['priority'])
                dict_character_appearances['hsk_level'].append(row['hsk_level'])
        df_character_appearances = pd.DataFrame(dict_character_appearances)
        df_character_appearances.to_csv('static/character_appearances.csv', index=False)
    return df_character_appearances

df_character_appearances = create_or_load_character_appearances()
print(len(df_character_appearances))
print(df_character_appearances['character'].value_counts().head(10))
df_character_appearances.tail()

Loading character appearances from static/character_appearances.csv
12741
character
人    96
大    93
子    82
不    73
生    57
一    52
心    52
中    52
上    52
学    50
Name: count, dtype: int64

      character word  priority  hsk_level
12736         出   作出       4.0        4.0
12737         作   作为       4.0        4.0
12738         为   作为       4.0        4.0
12739         做   做梦       4.0        4.0
12740         梦   做梦       4.0        4.0

# convert codename rulebook to csv

In [100]:
df_cn_raw = pd.read_csv('static/texts/raw/codenames_book_v1.tsv', delimiter='\t')[['chinese','pinyin', 'english']].dropna()
df_cn_raw.reset_index().to_csv('static/texts/lists/codenames_rulebook_v1.csv', index=False)

# remove duplicate characters from codenames

In [35]:
df_codenames = pd.read_csv('static/texts/lists/codenames_list_315.csv')
print(len(df_codenames))
df_all_vocab = pd.read_csv('static/latest_data.csv')
df_all_vocab = df_all_vocab[df_all_vocab['id'] <= 5867]
df_merged = df_codenames.merge(df_all_vocab[['chinese', 'id', 'voice_zh', 'voice_en']], on='chinese', how='left')
print(df_merged['id'].isna().sum(), len(df_codenames))
df_merged[pd.isna(df_merged['id'])].to_csv('static/texts/lists/codenames_list_315_add_to_sheet.csv', index=False)


df_all_vocab = pd.read_csv('static/latest_data.csv')
df_merged = df_codenames.merge(df_all_vocab[['chinese', 'id', 'voice_zh', 'voice_en']], on='chinese', how='left')
df_merged.to_csv('static/texts/lists/codenames_list_315_added_voice_cols.csv', index=False)

df_merged[pd.isna(df_merged['id'])].head()

315
232 315

Empty DataFrame
Columns: [index, chinese, pinyin, english, sentence, sentence_pinyin, sentence_english, id, voice_zh, voice_en]
Index: []

# resize image

In [34]:
from PIL import Image

size = 200, 100

im = Image.open('static/img/phonetic_icon_big.png')
im.thumbnail(size, Image.Resampling.LANCZOS)
im.save('static/img/phonetic_icon.png')

In [39]:
import numpy as np
df_all_vocab['sentence'] = df_all_vocab['sentence'].replace('-', np.nan)
df_all_vocab['sentence'].isna().sum()

np.int64(1327)

In [36]:
df_all_vocab['sentence'].isna().sum()

np.int64(1315)

# Create HSK column for MMD

In [4]:
# Import MMD
df_mmd = pd.read_csv('static/latest_data.csv')
df_mmd.head()

,id,chinese,pinyin,english,type,priority,category1,category2,cat_v3,cat2_v3,...,sentence_pinyin,sentence_english,date,source1,source2,funny,per,adu,slang,phonetic
0,1,房贷,fáng dài,mortgage,word,1,life,NaN,Finance & Economy,NaN,...,Ta měi gè yuè dōu yào huán fángdài,He has to pay his mortgage every month,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
1,2,白天,bái tiān,daytime,word,2,time,NaN,Time,NaN,...,Báitiān hěn rè wǎnshàng bǐjiào liángkuai,It is hot in the daytime and cooler at night,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
2,3,组成,zǔ chéng,to form;make up,word,3,general,NaN,Language & Expression,NaN,...,Shuǐ shì yóu qīng hé yǎng zǔchéng de,Water is made up of hydrogen and oxygen,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
3,4,组合,zǔ hé,combination,word,1,general,NaN,Work & Career,NaN,...,Zhège zǔhé zài bǐsài zhōng huòdé le dì yī míng.,This group won first place in the competition.,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN
4,5,保险,bǎo xiǎn,insurance,word,1,life,NaN,Finance & Economy,NaN,...,Méiyǒu bǎoxiǎn kànbìng hěn guì,It is expensive to see a doctor without insurance,2025-01-02,NaN,NaN,NaN,5.0,5.0,5.0,NaN

In [12]:
# Import HSK
df_hsk = pd.read_csv('static/hsk/hsk_1to6_sent.csv').drop_duplicates(subset=['chinese'])
df_hsk.sample(5)

,index,chinese,pinyin,english,sentence,sentence_pinyin,sentence_english,hsk3.0_def,video_notes,hsk_level
3731,3731,陪,péi,accompany,我会陪你去医院,wǒ huì péi nǐ qù yī yuàn,I will accompany you to the hospital,"companion, see, escort, accompany, keep ... co...","HSK3.0 definition: companion, see, escort, acc...",5
1796,1796,球迷,qiú mí,ball game fan,他是个忠实的足球迷。,tā shì gè zhōng shí de zú qiú mí.,He is a loyal soccer fan.,"fan (ball sports), CL:個|个[ge4]","HSK3.0 definition: fan (ball sports), CL:個|个[ge4]",3
390,390,下课,xià kè,to finish class,十点下课,shí diǎn xià kè,class finishes at ten,"finish class, get out of class","HSK3.0 definition: finish class, get out of class",1
3812,3812,人力,rén lì,manpower,完成这个项目需要大量人力,wán chéng zhè gè xiàng mù xū yào dà liàng rén lì,Completing this project requires a lot of manp...,"strength, manpower, resources, manual labor","HSK3.0 definition: strength, manpower, resourc...",5
4359,4359,长假,cháng jià,long holiday,我们计划暑假去旅行,wǒ men jì huà shǔ jià qù lǚ xíng,We plan to travel during the summer holiday,"long vacation, refers to one week national hol...","HSK3.0 definition: long vacation, refers to on...",6

In [13]:
df_mmdhsk = df_mmd[['id', 'chinese']].merge(df_hsk[['chinese', 'hsk_level']], how='left')
df_mmdhsk['hsk_level'] = df_mmdhsk['hsk_level'].fillna(-1).astype(int).astype(str).replace({'-1': 'NA'})
print(len(df_mmd), len(df_hsk), len(df_mmdhsk))
df_mmdhsk.head(10)

7600 5313 7600

   id chinese hsk_level
0   1      房贷        NA
1   2      白天         1
2   3      组成        NA
3   4      组合         3
4   5      保险         3
5   6     保险箱        NA
6   7      最初         4
7   8      离婚         3
8   9      创业         3
9  10      周一        NA

In [14]:
df_mmdhsk.to_csv('static/hsk/mmd_hsk_20260205.csv')